sudo: required
services:
  - docker

before_install:
  - docker build -t shadowglass/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true shadowglass/react-test npm test

after_success:
  - docker build -t shadowglass/multi-client ./client
  - docker build -t shadowglass/multi-nginx ./nginx
  - docker build -t shadowglass/multi-server ./server
  - docker build -t shadowglass/multi-worker ./worker
  # Log in
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push shadowglass/multi-client
  - docker push shadowglass/multi-nginx
  - docker push shadowglass/multi-server
  - docker push shadowglass/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-659168591895"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
